version: '3'

services:
  backend:
    build: ../backend
    ports:
      - "4000:4000"
    env_file:
      - ../backend/.env.example
  frontend:
    build: ../frontend
    ports:
      - "3000:3000"
    env_file:
      - ../frontend/.env.example
  ai:
    build: ../ai
    ports:
      - "5000:5000"
    env_file:
      - ../ai/.env.example
